version: '3.1'

name: 'bicycle'
services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 15248:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 12753:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: pass
      ME_CONFIG_MONGODB_URL: mongodb://root:pass@mongo:27017/
      ME_CONFIG_BASICAUTH: false

  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - 2376:1025
      - 8619:8025
    restart: always